feat: full orchestration of the variant index dag
opentargets/gentropy pull request #678
Opened 2024-07-09 10:24 UTC by ireneisdoomed

## ✨ Context
This PR describes changes in the business logic and the orchestration part to generate a full variant index starting with the defined inputs:
- Parquet files with credible sets generated by Gentropy
- Uniprot evidence file (pre ETL)
- PharmGKB evidence file (pre ETL)
- ClinVar evidence file (pre ETL)

and continuing to their annotation with VEP (more [here](https://github.com/opentargets/gentropy/pull/641))

## 🛠 What does this PR implement

- Generation of VCF files is done with Airflow. The sources to be included are configured with a YAML
- Annotation of variant coordinates from RSIDs with Ensembl API calls
- Implementation of a new step that takes one dataset containing variant info as input, and produces a valid VCF file
- Rearrangement of the tasks that annotate VCFs and produce a variant index from the VCF output into the variant index DAG
- Redefinition of variant ID: `ot_var_{hashed variant id}` for variants longer than 100 characters, `variant ID` for shorter variants as discussed with @d0choa and @DSuveges 

## 🙈 Missing

**There is a problem in the XCOM between the task that generates the list of files and the task that runs VEP. Listing the location of the VCFs is not returning anything and the annotation fails with `No files found to process.`**

@DSuveges , can you help me with this? It must be a tiny issue that I am not able to capture. I've tested the VCF files generation with a subset of data and it runs, and the same goes for the VEP annotation, so it's only this link between the 2 that is failing.

In the meantime I am going to start porting this logic to the orchestration layer.

## 🚦 Before submitting

- [ ] Do these changes cover one single feature (one change at a time)?
- [x] Did you read the [contributor guideline](https://opentargets.github.io/gentropy/development/contributing/#contributing-checklist)?
- [x] Did you make sure to update the documentation with your changes?
- [x] Did you make sure there is no commented out code in this PR?
- [x] Did you follow [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) standards in PR title and commit messages?
- [x] Did you make sure the branch is up-to-date with the `dev` branch?
- [ ] Did you write any new necessary tests?
- [x] Did you make sure the changes pass local tests (`make test`)?
- [x] Did you make sure the changes pass pre-commit rules (e.g `poetry run pre-commit run --all-files`)?

2024-07-09 12:28 UTC, DSuveges requested changes
OK, we can get back to this PR later.

2024-07-09 15:34 UTC, ireneisdoomed commented on src/gentropy/dataset/variant_index.py
> +
I think that this method is useful when you're operating with a variant index. I can move the logic to the ensembl datasource, and add a method in the variant index that calls it. What do you think?

2024-07-09 15:34 UTC, ireneisdoomed commented on src/gentropy/dataset/variant_index.py
> +    def assign_variant_id(
Is the implementation different?

2024-07-09 15:50 UTC, DSuveges commented on src/gentropy/dataset/variant_index.py
> +    def assign_variant_id(
[Somewhat](https://github.com/opentargets/gentropy/blob/cb7c384a28cb886b339c9e58494d1fd7c6bdafed/src/gentropy/dataset/variant_index.py#L63).

2024-07-09 19:13 UTC, DSuveges commented on src/gentropy/dataset/variant_index.py
> +
> I can move the logic to the ensembl datasource, and add a method in the variant index that calls it.
Why would a method in variant index call that method? If you are operating with variant index, you already have the coordinates. I can't see the usecase. Even if we were building a variant index based on a list of rsids.:

```python
vi = variant_index_from_rsids(rsid_list)
```

This logic should be living somewhere else. Just the returned value would be converted to vi dataset. To me, any method that does anything with API calls should live in a very special and isolated place.

2024-07-12 19:51 UTC, DSuveges approved these changes
There are some caveats of this implementation, but it works. Merging would unblock some variant index related work.

2024-07-12 19:51 UTC, merged