feat: add effect size direction to coloc output
opentargets/gentropy pull request #854
Opened 2024-10-17 13:16 UTC by Tobi1kenobi

## ✨ Context

Extracts the direction of effect from the study locus overlaps and appends it onto the colocalisation object.

## 🛠 What does this PR implement

Firstly adds a new method to StudyLocusOverlap to first calculate the ratio between each pair of left and right betas in each locus overlap. The sign of these betas is retained and then the averafe of these signs is returned as the output. See below diagram detailing process:
![image](https://github.com/user-attachments/assets/33e7cdc4-81c2-46cd-9f0f-e717a8cc69bb)

In theory this can return a value that is neither 1 or -1, however in practice this does not occur. See examples below when calculating overlaps between very large subsets of eQTL catalogue and a) Finngen
![image](https://github.com/user-attachments/assets/a1e27827-fc4b-44ed-a049-24bad94084c3)
or b) GWAS catalog
![image](https://github.com/user-attachments/assets/aea73002-50ec-4b36-8991-e70118d3b6bf)

Values between -1 and 1 could be captured by the front-end team if necessary and an acceptable threshold could be used e.g. beta_average_ratio > 0.8 = positive effect.

## 🙈 Missing

No extensive testing of edge cases, wasn't sure how best to implement and the testing for colocs isn't particularly extensive as it is so didn't want to add a lot of extra.

## 🚦 Before submitting

- [ ] Do these changes cover one single feature (one change at a time)?
- [ ] Did you read the [contributor guideline](https://opentargets.github.io/gentropy/development/contributing/#contributing-checklist)?
- [ ] Did you make sure to update the documentation with your changes?
- [ ] Did you make sure there is no commented out code in this PR?
- [ ] Did you follow [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) standards in PR title and commit messages?
- [ ] Did you make sure the branch is up-to-date with the `dev` branch?
- [ ] Did you write any new necessary tests?
- [ ] Did you make sure the changes pass local tests (`make test`)?
- [ ] Did you make sure the changes pass pre-commit rules (e.g `poetry run pre-commit run --all-files`)?

2024-10-18 12:56 UTC, d0choa commented
I added @DSuveges for review as well as there have been clashing changes coming from him

2024-10-28 13:34 UTC, addramir commented
Please add fillterning by 0, otherwise is good for me.

2024-10-29 10:10 UTC, addramir commented
@DSuveges  Have you had a chance to take a look?

2024-11-01 13:54 UTC, DSuveges requested changes
I don't really have objection with the logic. It looks good and makes sense. However I would recommend to apply small stylistic updates just to make the code style more aligned with the rest of the codebase.

2024-11-01 13:54 UTC, DSuveges commented on src/gentropy/dataset/study_locus_overlap.py
> +        expanded_overlaps = self.df.select("*", "statistics.*").drop("statistics")
I don't have objection about the logic in this function, however it is written in a quite different way than the other bits of the code. I would suggest collapsing the expressions as follows:

```python
return (
    # Unpack statistics column:
    self.df.select("*", "statistics.*")
    .drop("statistics")
    # Drop any rows where the beta is null or zero
    .filter(
        f.col("left_beta").isNotNull() & 
        f.col("right_beta").isNotNull() &
        (f.col("left_beta") != 0) &
        (f.col("right_beta") != 0) 
    )
    # Calculate the beta ratio and get the sign, then calculate the average sign across all variants in the locus
    .withColumn(
        "betaRatioSign",
        f.signum(f.col("left_beta") / f.col("right_beta"))
    )
    # Aggregate beta signs:
    .groupBy("leftStudyLocusId","rightStudyLocusId","chromosome")
    .agg(
        f.avg("betaRatioSign").alias("betaRatioSignAverage")
    )
)
```

2024-11-01 13:54 UTC, DSuveges commented on src/gentropy/method/colocalisation.py
> +                "left")
I know, these are positional arguments, but I like to be more explicit in joins by providing 

```python
.join(
    overlapping_signals.calculate_beta_ratio(),
    on=["leftStudyLocusId", "rightStudyLocusId","chromosome"],
    how="left"
)
```

2024-11-01 13:54 UTC, DSuveges commented on src/gentropy/method/colocalisation.py
> +                .join(overlapping_signals.calculate_beta_ratio(),
Same here.

2024-11-01 14:24 UTC, DSuveges approved these changes
Thanks. Looks good now.

2024-11-01 14:24 UTC, merged